spring:
  thymeleaf:
    # turn off cache for debugging
    cache: false
  mvc:
    favicon:
      enabled: false
  datasource:
    url: jdbc:mysql://localhost:3306/tw_search
    username: tty
    password: qwertyui
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: org.apache.commons.dbcp2.BasicDataSource
    tomcat:
      max-idle: 10
      max-active: 50
      max-wait: 10000
      initial-size: 5
  redis:
    jedis:
      pool:
        min-idle: 5
        max-active: 10
        max-idle: 10
        max-wait: 2000
    port: 6379
    host: 127.0.0.1
    password: 123456
    timeout: 1000
  servlet:
    multipart:
      max-file-size: 20000000
      max-request-size: 20000000
server:
  port: 8080
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.tty.twsearch.pojo